<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="octabot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find octabot_description)/urdf/octabot_gazebo_description.xacro"/>

  <xacro:property name="PI" value="3.142857143"/>
  <xacro:property name="deg2rad" value="0.017460317"/>
  <xacro:property name="cam_tilt_angle" value="87"/>   <!-- 87deg, h=0.11m, v=-0.02m -->
  <xacro:property name="cam_move_dist_h" value="0.11"/>
  <xacro:property name="cam_move_dist_v" value="-0.02"/>


  <material name="silver">
        <color rgba="0.4 0.4 0.4 1"/>
    </material>

  <material name="black">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>

  <material name="purple">
        <color rgba="1 0 1 1"/>
    </material>

  <material name="red">
        <color rgba="1 0 0 1"/>
    </material>




  <link name="world_frame"/>


  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0.085" rpy="0 0 0"/>
    <parent link="world_frame"/>
    <child link="chassis_link"/>
  </joint>




  <link name="chassis_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/new_chassis.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/chassis_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0887 0 0.06" rpy="0 0 0"/>
      <inertia
        ixx="0.1818" ixy="0.0" ixz="0.0"
        iyy="0.1818" iyz="0.0"
        izz="0.3276"
      />
    </inertial>
  </link>




  <joint name="left_wheel_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 0.163 -0.02" rpy="${-90 * deg2rad} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>





  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/wheel_case.dae"/>
      </geometry>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/wheel_130mm.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/wheel_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.00006" ixy="0.0" ixz="0.0"
        iyy="0.00006" iyz="0.0"
        izz="0.0004225"
      />
    </inertial>
  </link>



  <joint name="right_wheel_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 -0.163 -0.02" rpy="${-90 * deg2rad} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>




  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/wheel_case.dae"/>
      </geometry>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/wheel_130mm.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/wheel_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.00006" ixy="0.0" ixz="0.0"
        iyy="0.00006" iyz="0.0"
        izz="0.0004225"
      />
    </inertial>
  </link>




  <joint name="front_castor_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="front_castor_link"/>
    <origin xyz="0.17 0 -0.065" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>




  <link name="front_castor_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.000032" ixy="0.0" ixz="0.0"
        iyy="0.000032" iyz="0.0"
        izz="0.000032"
      />
    </inertial>
  </link>









  <joint name="cam_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="cam_link"/>
    <origin xyz="${cam_move_dist_h + 0.19} 0 ${cam_move_dist_v + 0.150}" rpy="0 ${cam_tilt_angle * deg2rad} 0"/>
    <axis xyz="0 1 0"/>
  </joint>


  <link name="cam_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/new_cam.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/cam_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.02"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.0000000002" ixy="0.0" ixz="0.0"
        iyy="0.0000000002" iyz="0.0"
        izz="0.00000000045"
      />
    </inertial>
  </link>






  <joint name="lidar_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.24" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <link name="lidar_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.035" length="0.035"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.02"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.0000004" ixy="0.0" ixz="0.0"
        iyy="0.0000004" iyz="0.0"
        izz="0.00001225"
      />
    </inertial>
  </link>  





  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.13" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <link name="imu_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.03 0.04 0.02"/>
      </geometry>
      <material name="purple"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.03 0.04 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.0002"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.0000000000000035" ixy="0.0" ixz="0.0"
        iyy="0.0000000000000035" iyz="0.0"
        izz="0.0000000000000109"
      />
    </inertial>
  </link>  








  <joint name="sonar1_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="sonar1_link"/>
    <origin xyz="0.205 0 0.10" rpy="0 0 ${0 * deg2rad}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="sonar1_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="1e-6" ixy="0.0" ixz="0.0"
        iyy="1e-6" iyz="0.0"
        izz="1e-6"
      />
    </inertial>
  </link>



  <joint name="sonar2_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="sonar2_link"/>
    <origin xyz="0.145 0.145 0.10" rpy="0 0 ${45 * deg2rad}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="sonar2_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="1e-6" ixy="0.0" ixz="0.0"
        iyy="1e-6" iyz="0.0"
        izz="1e-6"
      />
    </inertial>
  </link>



  <joint name="sonar3_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="sonar3_link"/>
    <origin xyz="-0.150 0 0.10" rpy="0 0 ${180 * deg2rad}"/>
    <axis xyz="0 0 1"/>
  </joint>


  <link name="sonar3_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="1e-6" ixy="0.0" ixz="0.0"
        iyy="1e-6" iyz="0.0"
        izz="1e-6"
      />
    </inertial>
  </link>





  <joint name="sonar4_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="sonar4_link"/>
    <origin xyz="0.145 -0.145 0.10" rpy="0 0 ${-45 * deg2rad}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="sonar4_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://octabot_description/meshes/sonar_collision.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="1e-6" ixy="0.0" ixz="0.0"
        iyy="1e-6" iyz="0.0"
        izz="1e-6"
      />
    </inertial>
  </link>


</robot>
